[package]
name = "advanced_pipeline"
version = "0.1.0"
edition = "2018"

[lib]
name = "advanced_pipeline"
path = "src/lib.rs"

[[bin]]
name = "advanced_pipeline"
path = "src/main.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
